name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:

env:
  PROJECT_ID: project-0d31fa55-9a98-4b08-860
  REGION: us-central1
  PATIENT_IMAGE: us-central1-docker.pkg.dev/project-0d31fa55-9a98-4b08-860/healthcare/patient-service:latest
  APPOINTMENT_IMAGE: us-central1-docker.pkg.dev/project-0d31fa55-9a98-4b08-860/healthcare/appointment-service:latest

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform fmt -check
      - run: terraform validate

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build & Push Images
        run: |
          docker build -t $PATIENT_IMAGE patient-service
          docker push $PATIENT_IMAGE

          docker build -t $APPOINTMENT_IMAGE appointment-service
          docker push $APPOINTMENT_IMAGE

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="patient_image=$PATIENT_IMAGE" \
            -var="appointment_image=$APPOINTMENT_IMAGE" 
