name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:

# REQUIRED for Workload Identity Federation (OIDC)
permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: hackton-488008
  PROJECT_NUMBER: 749003944857
  REGION: us-central1

  PATIENT_IMAGE: us-central1-docker.pkg.dev/hackton-488008/healthcare/patient-service:latest
  APPOINTMENT_IMAGE: us-central1-docker.pkg.dev/hackton-488008/healthcare/appointment-service:latest

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        working-directory: healthcare-microservices/terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: healthcare-microservices/terraform
        run: |
          terraform init -backend=false
          terraform validate

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using OIDC
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/749003944857/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa-project-0d31@hackton-488008.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & Push Patient Service Image
        run: |
          docker build -t $PATIENT_IMAGE healthcare-microservices/patient-service
          docker push $PATIENT_IMAGE

      - name: Build & Push Appointment Service Image
        run: |
          docker build -t $APPOINTMENT_IMAGE healthcare-microservices/appointment-service
          docker push $APPOINTMENT_IMAGE

      - name: Terraform Apply (Deploy Cloud Run)
        working-directory: healthcare-microservices/terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="patient_image=$PATIENT_IMAGE" \
            -var="appointment_image=$APPOINTMENT_IMAGE"
