name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: hackton-488008
  REGION: us-central1
  PATIENT_IMAGE: us-central1-docker.pkg.dev/hackton-488008/healthcare/patient-service:latest
  APPOINTMENT_IMAGE: us-central1-docker.pkg.dev/hackton-488008/healthcare/appointment-service:latest

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: terraform fmt -check
      - run: terraform validate

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      # üîê OIDC Authentication (NO JSON KEYS)
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@hackton-488008.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & Push Images
        run: |
          docker build -t $PATIENT_IMAGE patient-service
          docker push $PATIENT_IMAGE

          docker build -t $APPOINTMENT_IMAGE appointment-service
          docker push $APPOINTMENT_IMAGE

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="patient_image=$PATIENT_IMAGE" \
            -var="appointment_image=$APPOINTMENT_IMAGE"